### ISSUE TITLE
multiple publishers in single file

### ISSUE THREAD

**Issue by rettinghaus** [TEI-Correspondence-SIG/CMIF#13]
When having multiple `publisher` elements a file will not validate against the RNG. 
As TEI allows multiple publishers in `<publicationStmt>` CMIF should do so, too.

**Comment by StefanDumont** [comment]
That's right, Klaus. The ODD and RNG is now modified to allow multiple publisher elements.

**Comment by rettinghaus** [comment]
Thanks!
