### ISSUE TITLE
make RelaxNG more accessible

### ISSUE THREAD

**Issue by rettinghaus** [TEI-Correspondence-SIG/CMIF#15]
If you want to use the cmi-customization.rng (without downloading), you have to use this URL: 
`https://raw.githubusercontent.com/TEI-Correspondence-SIG/CMIF/master/schema/cmi-customization.rng`

It would be nice to have a somewhat more "official" URL for this.

**Comment by peterstadler** [comment]
During SIG meeting at Tokyo we agree that the above URL is not very nice and neither intuitive but alternative proposals weren't convincing either.

In fact, a major advantage of the current schema location is that it stresses the fact that it's a community (SIG) effort and it can be available in different versions (tags).
