### ISSUE TITLE
ODD still unstable?

### ISSUE THREAD

**Issue by rettinghaus** [TEI-Correspondence-SIG/CMIF#17]
The current ODD is still marked with `status="unstable"`. Seems to me, it is quite stable now. 😃 

In addition, the latest changes aren't documented in `<revisionDesc>`. This should be completed.

**Comment by StefanDumont** [comment]
Thanks for the hint, I'll fix it ...

**Comment by rettinghaus** [comment]
Gentle reminder ;-)
