### ISSUE TITLE
Where to note an ID of a letter?

### ISSUE THREAD

**Issue by peterstadler** [TEI-Correspondence-SIG/CMIF#2]
Original issue raised at https://github.com/TEI-Correspondence-SIG/correspDesc/issues/3 by @StefanDumont 

> In the correspDesc customization for interchange proposes ("correspBeacon") we're using `@ref` to store the URL of an edited letter. For other URLS (e.g. facsimile) we have projected to use `@corresp`. But to note an ID number of a letter there is no solution at the moment. Perhaps we can use `@key` for that purpose? It is also member of att.canonical (like `@ref`).

**Comment by peterstadler** [comment]
@StefanDumont: technically, `@key` is already allowed at `<correspDesc>`. Is this ticket rather for documentation than implementation?

**Comment by StefanDumont** [comment]
I didn't see that it was already implemented in the ODD. Than everything is allright!
