### ISSUE TITLE
allow att.datable.iso

### ISSUE THREAD

**Issue by rettinghaus** [TEI-Correspondence-SIG/CMIF#22]
Why is `att.datable.iso` not available, although correspSearch can't process all allowed values of `att.datable.w3c`?

**Comment by peterstadler** [comment]
`att.datable.iso` is a **super**set of `att.datable.w3c` and IMHO it's good to keep these date formats as constrained as possible. In our WeGA ODD I even constrain `att.datable.w3c` to only allow `xs:gYear` and `xs:date`, see https://github.com/Edirom/WeGA-ODD/blob/d7bb8b3208187bdd23d102911987cbb10957c411/src/Specs/common-specs.odd.xml#L377

So, I think it's appropriate for CMIF to not allow  `att.datable.iso` -- but maybe I miss your point?

**Comment by rettinghaus** [comment]
D'oh! I thought `att.datable.w3c` was a superset of `att.datable.iso`.
