### ISSUE TITLE
typing errors in doc

### ISSUE THREAD

**Issue by wobweger** [TEI-Correspondence-SIG/CMIF#25]
`./doc/documentation-en.md` has to minor typing errors.

+ line 12 Guidelines (Guidlines)
+ line 17 addressee (addresssee)

**Comment by wobweger** [comment]
+ line 44 recommended (recommende)

**Comment by pdaengeli** [comment]
* spurious `#` in [`L235`](https://github.com/TEI-Correspondence-SIG/CMIF/blob/c99f733/doc/documentation-en.xml#L235): "c3f497f0-488d-4233-9448-130ba8109bd8" ("#c3f497f0-488d-4233-9448-130ba8109bd8")

**Comment by peterstadler** [comment]
Thank you @wobweger and @pdaengeli for the notification!
