### ISSUE TITLE
allow multiple tei:bibl as beacon source 

### ISSUE THREAD

**Issue by peterstadler** [TEI-Correspondence-SIG/CMIF#3]
Original issue raised at https://github.com/TEI-Correspondence-SIG/correspDesc/issues/7 

> This has been raised by @rettinghaus:
> When you're creating an index of letters this might as well be a 'meta catalogue' comprising of several editions. Thus it would be helpful to allow several \<tei:bibl\> within \<tei:sourceDesc\> to point at from the \<tei:correspDesc\> entries.

**Comment by peterstadler** [comment]
Done.
(Referenced the wrong issue at 16547d34852de1691a130e119b63be49979c8aeb)

**Comment by StefanDumont** [comment]
Just for the documentation: the attribute correspDesc/@source is intended for referencing to one of the tei:bibl/@xml:id. At the moment, the TEI Guidelines doesn't allow it in correspDesc, but it will be a member of att.global in the next release (see https://github.com/TEIC/TEI/issues/536)
